#!/usr/bin/env python3.6
#
# This file is part of gotoupsd.
#
# gotoupsd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# gotoupsd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with powerd.  If not, see <http://www.gnu.org/licenses/>.

# pylint: disable=broad-except
# pylint: disable=too-few-public-methods

"""Frontend for querying the GOTO UPSes via SNMP."""

import datetime
import Pyro4
from warwick.observatory.common import (
    daemons,
    log)

from warwick.observatory.power import (
    SNMPDevice,
    APCUPSStatusParameter,
    APCUPSBatteryRemainingParameter,
    APCUPSBatteryHealthyParameter,
    APCUPSOutputLoadParameter)

# Timeout in seconds for SNMP commands
SNMP_TIMEOUT = 2

MAIN_UPS_IP = '10.2.6.1'
MAIN_UPS_PARAMETERS = [
    APCUPSStatusParameter('main_ups_status'),
    APCUPSBatteryRemainingParameter('main_ups_battery_remaining'),
    APCUPSBatteryHealthyParameter('main_ups_battery_healthy'),
    APCUPSOutputLoadParameter('main_ups_load'),
]

DOME_UPS_IP = '10.2.6.2'
DOME_UPS_PARAMETERS = [
    APCUPSStatusParameter('dome_ups_status'),
    APCUPSBatteryRemainingParameter('dome_ups_battery_remaining'),
    APCUPSBatteryHealthyParameter('dome_ups_battery_healthy'),
    APCUPSOutputLoadParameter('dome_ups_load'),
]

class UPSMonitorDaemon:
    """Wraps a SNMP request to the UPSes"""
    def __init__(self):
        self._connection_error = False
        self._devices = [
            SNMPDevice(MAIN_UPS_IP, MAIN_UPS_PARAMETERS, SNMP_TIMEOUT),
            SNMPDevice(DOME_UPS_IP, DOME_UPS_PARAMETERS, SNMP_TIMEOUT),
        ]

        # Map of parameter name to device holding the parameter
        self._device_by_parameter = {}
        for device in self._devices:
            for parameter in device.parameters:
                self._device_by_parameter.update({parameter.name: device})

    @Pyro4.expose
    def last_measurement(self):
        """Query the latest valid measurement.
        May return None if no data is available"""
        try:
            data = {'date': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')}
            for device in self._devices:
                data.update(device.status())

            if self._connection_error:
                log.info('gotoupsd', 'Restored connection to UPSes')
                self._connection_error = False
            return data

        except Exception as exception:
            print('{} ERROR: failed to query SNMP: {}' \
                  .format(datetime.datetime.utcnow(), str(exception)))

            if not self._connection_error:
                log.error('gotoupsd', 'Lost connection to UPSes')
                self._connection_error = True

            return None

if __name__ == '__main__':
    daemons.goto_ups.launch(UPSMonitorDaemon())
